version: "3"
services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
      - LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - RESTREVIEWS_DB_URI=${RESTREVIEWS_DB_URI}
      - RESTREVIEWS_NS=${RESTREVIEWS_NS}
      - PORT=5000
    volumes:
      - ./server:/index
      - ./server:/node_modules
    depends_on:
      - mongodb
    env_file:
      - ./server/.env 

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
    stdin_open: true
    tty: true
    depends_on:
      - server
    env_file:
      - ./client/.env 
